#!/bin/sh
# Note: this script is sourced by Jenkins, which has the auto-detected PTXdist
# version symlinked to ./p
case "${JOB_BASE_NAME}" in
	*v8a*)
		[ -e selected_toolchain_r5 ] || {
			# store away the currently selected toolchain
			[ -e selected_toolchain ] && mv selected_toolchain selected_toolchain_ci_backup
			# create toolchain based on v7a platform, which is needed for R5 processor.
			./p toolchain --platformconfig=configs/platform-v7a/platformconfig
			mv selected_toolchain selected_toolchain_r5
			# restore the selected toolchain, if there was one before
			[ -e selected_toolchain_ci_backup ] && mv selected_toolchain_ci_backup selected_toolchain
		}
		;;
esac
